import { EditorView } from '@codemirror/view'
import { HighlightStyle, syntaxHighlighting } from '@codemirror/language'
import { tags } from '@lezer/highlight'

// Catppuccin palette — Mocha (dark) & Latte (light), as used in catppuccin/nvim
const catppuccin = {
  mocha: { // dark
    base:    '#1e1e2e',
    mantle:  '#181825',
    surface0:'#313244',
    surface1:'#45475a',
    overlay0:'#6c7086',
    text:    '#cdd6f4',
    subtext1:'#bac2de',
    subtext0:'#a6adc8',
    rosewater:'#f5e0dc',
    flamingo: '#f2cdcd',
    pink:    '#f38ba8',
    mauve:   '#cba6f7',
    red:     '#f38ba8',
    maroon:  '#eba0ac',
    peach:   '#fab387',
    yellow:  '#f9e2af',
    green:   '#a6e3a1',
    teal:    '#94e2d5',
    sky:     '#89dceb',
    sapphire:'#74c7ec',
    blue:    '#89b4fa',
    lavender:'#b4befe',
    selection:'rgba(69, 71, 90, 0.6)',
  },
  latte: { // light
    base:    '#eff1f5',
    mantle:  '#e6e9ef',
    surface0:'#ccd0da',
    surface1:'#bcc0cc',
    overlay0:'#9ca0b0',
    text:    '#4c4f69',
    subtext1:'#5c5f77',
    subtext0:'#6c6f85',
    rosewater:'#dc8a78',
    flamingo: '#dd7878',
    pink:    '#ea76cb',
    mauve:   '#8839ef',
    red:     '#d20f39',
    maroon:  '#e64553',
    peach:   '#fe640b',
    yellow:  '#df8e1d',
    green:   '#40a02b',
    teal:    '#179299',
    sky:     '#04a5e5',
    sapphire:'#209fb5',
    blue:    '#1e66f5',
    lavender:'#7287fd',
    selection:'rgba(204, 208, 218, 0.7)',
  }
}

const catppuccinMochaSyntax = HighlightStyle.define([
  { tag: tags.heading1, color: catppuccin.mocha.mauve,   fontWeight: '800', fontSize: '1.62em' },
  { tag: tags.heading2, color: catppuccin.mocha.mauve,   fontWeight: '760', fontSize: '1.38em' },
  { tag: tags.heading3, color: catppuccin.mocha.mauve,   fontWeight: '720', fontSize: '1.22em' },
  { tag: tags.heading4, color: catppuccin.mocha.mauve,   fontWeight: '700', fontSize: '1.1em' },
  { tag: tags.heading5, color: catppuccin.mocha.mauve,   fontWeight: '680' },
  { tag: tags.heading6, color: catppuccin.mocha.subtext0,fontWeight: '680' },
  { tag: tags.strong,      fontWeight: '700', color: catppuccin.mocha.peach },
  { tag: tags.emphasis,    fontStyle: 'italic', color: catppuccin.mocha.teal },
  { tag: tags.strikethrough, textDecoration: 'line-through', color: catppuccin.mocha.overlay0 },
  { tag: tags.link,        color: catppuccin.mocha.sapphire, textDecoration: 'underline' },
  { tag: tags.url,         color: catppuccin.mocha.sapphire, textDecoration: 'underline' },
  { tag: tags.quote,       color: catppuccin.mocha.teal, fontStyle: 'italic' },
  { tag: tags.keyword,     color: catppuccin.mocha.mauve,   fontWeight: 'bold' },
  { tag: tags.string,      color: catppuccin.mocha.green },
  { tag: tags.number,      color: catppuccin.mocha.peach },
  { tag: tags.bool,        color: catppuccin.mocha.peach },
  { tag: tags.null,        color: catppuccin.mocha.mauve },
  { tag: tags.comment,     color: catppuccin.mocha.overlay0, fontStyle: 'italic' },
  { tag: tags.operator,    color: catppuccin.mocha.sky },
  { tag: tags.punctuation, color: catppuccin.mocha.subtext1 },
  { tag: tags.bracket,     color: catppuccin.mocha.subtext1 },
  { tag: tags.variableName,color: catppuccin.mocha.text },
  { tag: tags.function(tags.variableName), color: catppuccin.mocha.blue, fontWeight: 'bold' },
  { tag: tags.definition(tags.variableName), color: catppuccin.mocha.lavender },
  { tag: tags.typeName,    color: catppuccin.mocha.yellow, fontStyle: 'italic' },
  { tag: tags.className,   color: catppuccin.mocha.yellow, fontStyle: 'italic' },
  { tag: tags.propertyName,color: catppuccin.mocha.blue },
  { tag: tags.atom,        color: catppuccin.mocha.flamingo },
  { tag: tags.meta,        color: catppuccin.mocha.overlay0 },
  { tag: tags.regexp,      color: catppuccin.mocha.red },
  { tag: tags.escape,      color: catppuccin.mocha.pink },
])

const catppuccinLatteSyntax = HighlightStyle.define([
  { tag: tags.heading1, color: catppuccin.latte.mauve,   fontWeight: '800', fontSize: '1.62em' },
  { tag: tags.heading2, color: catppuccin.latte.mauve,   fontWeight: '760', fontSize: '1.38em' },
  { tag: tags.heading3, color: catppuccin.latte.mauve,   fontWeight: '720', fontSize: '1.22em' },
  { tag: tags.heading4, color: catppuccin.latte.mauve,   fontWeight: '700', fontSize: '1.1em' },
  { tag: tags.heading5, color: catppuccin.latte.mauve,   fontWeight: '680' },
  { tag: tags.heading6, color: catppuccin.latte.subtext0,fontWeight: '680' },
  { tag: tags.strong,      fontWeight: '700', color: catppuccin.latte.peach },
  { tag: tags.emphasis,    fontStyle: 'italic', color: catppuccin.latte.teal },
  { tag: tags.strikethrough, textDecoration: 'line-through', color: catppuccin.latte.overlay0 },
  { tag: tags.link,        color: catppuccin.latte.sapphire, textDecoration: 'underline' },
  { tag: tags.url,         color: catppuccin.latte.sapphire, textDecoration: 'underline' },
  { tag: tags.quote,       color: catppuccin.latte.teal, fontStyle: 'italic' },
  { tag: tags.keyword,     color: catppuccin.latte.mauve,   fontWeight: 'bold' },
  { tag: tags.string,      color: catppuccin.latte.green },
  { tag: tags.number,      color: catppuccin.latte.peach },
  { tag: tags.bool,        color: catppuccin.latte.peach },
  { tag: tags.null,        color: catppuccin.latte.mauve },
  { tag: tags.comment,     color: catppuccin.latte.overlay0, fontStyle: 'italic' },
  { tag: tags.operator,    color: catppuccin.latte.sky },
  { tag: tags.punctuation, color: catppuccin.latte.subtext1 },
  { tag: tags.bracket,     color: catppuccin.latte.subtext1 },
  { tag: tags.variableName,color: catppuccin.latte.text },
  { tag: tags.function(tags.variableName), color: catppuccin.latte.blue, fontWeight: 'bold' },
  { tag: tags.definition(tags.variableName), color: catppuccin.latte.lavender },
  { tag: tags.typeName,    color: catppuccin.latte.yellow, fontStyle: 'italic' },
  { tag: tags.className,   color: catppuccin.latte.yellow, fontStyle: 'italic' },
  { tag: tags.propertyName,color: catppuccin.latte.blue },
  { tag: tags.atom,        color: catppuccin.latte.flamingo },
  { tag: tags.meta,        color: catppuccin.latte.overlay0 },
  { tag: tags.regexp,      color: catppuccin.latte.red },
  { tag: tags.escape,      color: catppuccin.latte.pink },
])

export const catppuccinDark = [
  EditorView.theme(
    {
      '&': {
        backgroundColor: catppuccin.mocha.base,
        color: catppuccin.mocha.text,
      },
      '.cm-content': { caretColor: catppuccin.mocha.rosewater },
      '.cm-cursor, .cm-dropcursor': { borderLeftColor: catppuccin.mocha.rosewater },
      '.cm-gutters': {
        backgroundColor: catppuccin.mocha.base,
        color: catppuccin.mocha.overlay0,
        borderRight: `1px solid ${catppuccin.mocha.surface0}`,
      },
      '.cm-relativeLineNumbers': {
        backgroundColor: catppuccin.mocha.base,
      },
      '.cm-selectionBackground': { backgroundColor: catppuccin.mocha.selection },
      '&.cm-focused .cm-selectionBackground': { backgroundColor: catppuccin.mocha.selection },
    },
    { dark: true }
  ),
  syntaxHighlighting(catppuccinMochaSyntax),
]

export const catppuccinLight = [
  EditorView.theme(
    {
      '&': {
        backgroundColor: catppuccin.latte.base,
        color: catppuccin.latte.text,
      },
      '.cm-content': { caretColor: catppuccin.latte.rosewater },
      '.cm-cursor, .cm-dropcursor': { borderLeftColor: catppuccin.latte.rosewater },
      '.cm-gutters': {
        backgroundColor: catppuccin.latte.base,
        color: catppuccin.latte.overlay0,
        borderRight: `1px solid ${catppuccin.latte.surface0}`,
      },
      '.cm-relativeLineNumbers': {
        backgroundColor: catppuccin.latte.base,
      },
      '.cm-selectionBackground': { backgroundColor: catppuccin.latte.selection },
      '&.cm-focused .cm-selectionBackground': { backgroundColor: catppuccin.latte.selection },
    },
    { dark: false }
  ),
  syntaxHighlighting(catppuccinLatteSyntax),
]
