export const MIN_FOLDER_PANEL_WIDTH = 120
export const MAX_FOLDER_PANEL_WIDTH = 320
export const MIN_NOTES_PANEL_WIDTH = 220
export const SIDEBAR_PANEL_DIVIDER_WIDTH = 4

export const MIN_SIDEBAR_WIDTH = 200

